# Generated by Django 5.2.1 on 2025-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0002_episodio_thumb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodio",
            name="thumb",
            field=models.URLField(),
        ),
    ]
